---
title: "Health Expenditure_PJ"
output: 
  flexdashboard::flex_dashboard:
  orientation: columns
vertical_layout: fill
---
Health Expenditure
  
```{r setup, include=FALSE}
library(flexdashboard)
install.packages("tmap")
install.packages("terra")
library(tmap)
library(terra)

install.packages("sf")
install.packages("stars")
library("stars")
library("sf")

remotes::install_github("r-spatial/stars")
remotes::install_github("r-spatial/sf")
```




```{r}
health_exp_cases <- readRDS("df_health_expenditure_cases.RDS")
View(health_exp_cases)
health_exp_deaths <- readRDS("df_health_expenditure_deaths.RDS")

data("World")
tm_shape(World) +
    tm_polygons("HPI")

tmap_mode("view")
library(maps)
data(world.cities)
tm_shape(World) +
    tm_polygons("HPI")

```


```{r}
devtools::install_github("rstudio/leaflet")

library(leaflet)

m <- leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=174.768, lat=-36.852, popup="The birthplace of R")
m  # Print the map

```

